name: 'Wordpress Updater'
description: 'Update Wordpress download URLs in repo with using GitHub Actions'
inputs:
  github_token:
    description: 'secrets.GITHUB_TOKEN'
    required: true
  targets:
    description: 'Path of files to check'
    required: true
  check_core:
    description: 'Check core updates if true'
    required: false
    default: true
  core_locale:
    description: 'Filter core by locale'
    required: false
    default: null
runs:
  using: 'node18'
  main: 'dist/index.js'
