name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  targets:
    description: 'Path of files to check'
    required: true
  check_core:
    description: 'Check core updates if true'
    required: false
    default: true
  core_locale:
    description: 'Filter core by locale'
    required: false
    default: null
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
